title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

domain: joshcampbell191.github.io
baseurl: "/jekyll-theme-bootstrap" # the subpath of your site, e.g. /blog
url: https://joshcampbell191.github.io # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true # set to true to show excerpts on the homepage

# Bootstrap date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
bootstrap:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: devto,          title: "DEV",             user_url: "https://dev.to/jekyll" }
    - { platform: dribbble,       title: "Dribbble",        user_url: "https://dribbble.com/jekyll" }
    - { platform: facebook,       title: "Facebook",        user_url: "https://www.facebook.com/jekyll" }
    - { platform: flickr,         title: "Flickr",          user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         title: "GitHub",          user_url: "https://github.com/jekyll/minima" }
    - { platform: google_scholar, title: "Google Scholar",  user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      title: "Instagram",       user_url: "https://www.instagram.com/jekyll" }
    - { platform: keybase,        title: "Keybase",         user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       title: "LinkedIn",        user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: microdotblog,   title: "Micro.blog",      user_url: "https://micro.blog/jekyll" }
    - { platform: pinterest,      title: "Pinterest",       user_url: "https://www.pinterest.com/jekyll" }
    - { platform: rss,            title: "RSS",             user_url: "/feed.xml" }
    - { platform: stackoverflow,  title: "Stack Overflow",  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    - { platform: telegram,       title: "Telegram",        user_url: "https://t.me/jekyll" }
    - { platform: twitter,        title: "Twitter",         user_url: "https://twitter.com/jekyllrb" }
    - { platform: youtube,        title: "YouTube",         user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#
# header_pages:
#   - about.md

# Build settings
theme: jekyll-theme-bootstrap

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
